background = 000000
foreground = a6a6a6

# Normal colors
palette = 0=#3B4252
palette = 1=#BF616A
palette = 2=#A3BE8C
palette = 3=#EBCB8B
palette = 4=#81A1C1
palette = 5=#B48EAD
palette = 6=#88C0D0
palette = 7=#E5E9F0

# Bright colors
palette = 8=#4C566A
palette = 9=#BF616A
palette = 10=#A3BE8C
palette = 11=#EBCB8B
palette = 12=#81A1C1
palette = 13=#B48EAD
palette = 14=#8FBCBB
palette = 15=#808080
