[general]
live_config_reload = true

import = [
  "~/.config/alacritty/keys.toml",
  "~/.config/alacritty/petro-colors.toml",
  # "~/.config/alacritty/comic-font.toml",
  "~/.config/alacritty/comic-nerd-font.toml"
  # "~/.config/alacritty/nerd-font.toml"
  # "~/.config/alacritty/pragmata-pro-font.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
opacity = 1.9

[window.padding]
x = 5
y = 5
