[[keyboard.bindings]]
key = "Comma"
mods = "Command"

[keyboard.bindings.command]
args = ["~/.config/alacritty/alacritty.yml"]
program = "/opt/homebrew/bin/nvim"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = """
\u0002
"""
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002j"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002k"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002-"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\\"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002H"
key = "H"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002J"
key = "J"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002K"
key = "K"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002L"
key = "L"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002u"
key = "M"
mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002["
# key = "Apostrophe"
# mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

# send ctrl-b followed by ctlr-l to trigger the command in tmux
# use xxd to figure out the mapping for ctrl-l
[[keyboard.bindings]]
chars = "\u0002\u000c"
key = ";"
mods = "Command"
