[font.bold]
family = "Essential PragmataPro"
style = "Regular"

[font.italic]
family = "Essential PragmataPro"
style = "Regular"

[font.normal]
family = "Essential PragmataPro"
style = "Regular"

[font]
size = 12.0

[font.offset]
x = 0
y = 2
